// product modal
    function openProduct(id){const p=PRODUCTS.find(p=>p.id===id);document.getElementById('productModalBody').innerHTML=`<div class="product-modal-grid"><img src="${p.image}" alt="${p.brand} ${p.model}"><div><div class="product-brand">${p.brand} · ${p.model}</div><h2>${p.title}</h2><div class="availability" style="${p.stock?'':'color:#8b95a0'}">${p.stock?'Есть в наличии':'Наличие уточнит менеджер'}</div><div class="detail-specs"><div class="detail-spec"><small>Квадрат</small><b>${p.square}</b></div><div class="detail-spec"><small>Момент</small><b>${p.torque} Н·м</b></div><div class="detail-spec"><small>Вес</small><b>${p.weight} кг</b></div><div class="detail-spec"><small>Упаковка</small><b>${p.dims}</b></div></div><p class="muted" style="line-height:1.6">${p.why}</p><div class="price" style="font-size:32px;margin:20px 0">${fmt(p.price)}</div><button class="btn blue" onclick="addToCart('${p.id}');closeModalOnly('productModal')">Добавить в корзину +</button></div></div>`;openModal('productModal')}
    function openModal(id){const m=document.getElementById(id);m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
    function closeModalOnly(id){const m=document.getElementById(id);m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')}
    document.querySelectorAll('.modal-close').forEach(b=>b.onclick=()=>closeModalOnly(b.closest('.modal').id));
    document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModalOnly(m.id)}));

    // checkout
    document.getElementById('checkoutBtn').onclick=()=>{if(!cart.length)return;drawer.classList.remove('open');overlay.classList.remove('open');renderSummary();openModal('checkoutModal')};
    function renderSummary(){document.getElementById('summaryItems').innerHTML=cart.map(x=>{const p=PRODUCTS.find(p=>p.id===x.id);return `<div class="summary-item"><strong>${p.brand} ${p.model} × ${x.qty}</strong><span>${fmt(p.price*x.qty)}</span></div>`}).join('');document.getElementById('summaryTotal').textContent=fmt(cartTotal())}
    let buyer='person';document.querySelectorAll('[data-buyer]').forEach(b=>b.onclick=()=>{buyer=b.dataset.buyer;document.querySelectorAll('[data-buyer]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('legalFields').classList.toggle('show',buyer==='company');document.getElementById('invoiceCheck').style.display=buyer==='company'?'flex':'none'});
    const delivery=document.getElementById('deliverySelect');delivery.onchange=()=>{document.getElementById('addressField').style.display=delivery.value==='Самовывоз'?'none':'grid'};
    document.getElementById('checkoutForm').addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;const fd=new FormData(e.currentTarget);const order='RSP-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+String(Date.now()).slice(-5);let body=`Заказ ${order}\nДата: ${new Date().toLocaleString('ru-RU')}\n\nПокупатель: ${buyer==='company'?'Компания':'Физическое лицо'}\nИмя: ${fd.get('name')}\nТелефон: ${fd.get('phone')}\nEmail: ${fd.get('email')}\nГород: ${fd.get('city')}\n`;if(buyer==='company')body+=`Компания: ${fd.get('company')||'—'}\nИНН: ${fd.get('inn')||'—'}\nНужен счёт: ${fd.get('invoice')?'Да':'Нет'}\n`;body+=`\nПолучение: ${fd.get('delivery')}\nАдрес/комментарий: ${fd.get('address')||'—'}\n\nСостав заказа:\n`;cart.forEach(x=>{const p=PRODUCTS.find(p=>p.id===x.id);body+=`• ${p.brand} ${p.model} — ${x.qty} шт. × ${fmt(p.price)} = ${fmt(p.price*x.qty)}\n`});body+=`\nИтого товары: ${fmt(cartTotal())}\nДоставка: уточняет менеджер\nКомментарий: ${fd.get('comment')||'—'}\n`;const subject=`Заказ с лендинга ${order}`;document.getElementById('checkoutStatus').className='status good';document.getElementById('checkoutStatus').textContent='Заказ сформирован. Сейчас откроется письмо — отправьте его, чтобы данные поступили менеджеру.';location.href=`mailto:a.tokarev@respotec.ru?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
